apiVersion: v1
kind: Service
metadata:
  name: "{{ include "visops.fullname" . | trim }}-rabbitmq-service"
spec:
  selector:
    app: "{{ include "visops.fullname" . | trim }}"
  type: {{ .Values.service.type }}
  ports:
    {{- range .Values.rabbitmq.service.ports }}
    - name: {{ .name }}
      port: {{ .targetPort }}
      targetPort: {{ .targetPort }}
    {{- end }}
  selector:
    app: "{{ include "visops.fullname" . | trim }}-rabbitmq-deployment"
