apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "visops.fullname" . | trim }}-secret"
  labels:
    app: "{{ include "visops.fullname" . | trim }}"
type: Opaque
data:
    DATABASE_URL: "postgres://{{ .Values.postgresql.auth.username }}:{{ .Values.postgresql.auth.password }}@{{ .Values.postgresql.host }}:5432/{{ .Values.postgresql.auth.database }}"
    AUTH_SECRET: "your_auth_secret"
    RABBITMQ_URL: "amqp://{{ .Values.rabbitmq.auth.username }}:{{ .Values.rabbitmq.auth.password }}@{{ include "visops.fullname" . | trim }}-rabbitmq-service:5672"